### PR TITLE
Kevin list customers

### PR DESCRIPTION
**Pull request by neodroid**
- Create test cases for list all customers
- Create endpoint to list all customers

### CODE REVIEW

**Review by DIVYANSHI-PARASHAR — CHANGES_REQUESTED** [review]
You have to remove the fields that are not in our database and tailor the function to list customer base on our database fields. In service/routes.py:
Remove the category and name- add id and first_name and replace the method names with what we have in our models.py (class methods at the end of the file- find, find_by_name)

In models.py- I would suggest changing the method names- "find" to "find_by_id", "find_by_name" to "find_by_firstname"

Then in routes.py:
Paste this- 
customer_id = request.args.get("id")
    first_name = request.args.get("first_name")
    if customer_id:
        customers = Customer.find_by_id(customer_id)
    elif name:
        customers = Customer.find_by_firstname(first_name)
    else:
        customers = Customer.all()

**Comment by DIVYANSHI-PARASHAR** [comment]
You can also add other methods to find using other fields as well.
Also, don't forget to test!

**Comment by neodroid** [comment]
@DIVYANSHI-PARASHAR I changed the filter to make it only list ALL of the customers, my bad not noticing the query, i fixed it!. 

and for the queries i think that is out of scope for this issue since the task is to list all of the customer (without pagination and queries) also, the find() is used on the 'Read a customer' part so i think if we want to change the function name its better to make a separate issue just like the query. wdyt?

**Comment by DIVYANSHI-PARASHAR** [comment]
Agreed! We can make a separate issue for queries or we can maybe modify the account search functionality issue as well in the product backlog.

**Review by DIVYANSHI-PARASHAR — APPROVED** [review]

**Pull request merged**
